script:
    - yarn run test-only

after_success:
    - yarn run typedoc
    - yarn pack

deploy:
    - provider: pages
      skip_cleanup: true
      local_dir: docs/
      github_token: $GITHUB_TOKEN
      on:
          tags: true
    - provider: releases
      api_key: $GITHUB_TOKEN
      file_glob: true
      file: "{YOURLIB}-*.tgz"
      skip_cleanup: true
      on:
          tags: true
    - provider: yarn
      skip_cleanup: true
      email: "qasim9872@gmail.com"
      api_key: $NPM_TOKEN
      on:
          tags: true
